services:
  - type: web
    name: biblioteca_ceb
    env: python
    plan: free  
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn biblioteca_ceb.wsgi:application --worker-tmp-dir /dev/shm"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: biblioteca_ceb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        sync: false # Sync significa que puedes actualizar el valor sin hacer redeploy; pon false para producción
        value: tu-secreto-para-produccion
    autoDeploy: true
    healthCheckPath: /
    region: oregon
    buildScript: ./render-build.sh
    dockerfilePath: Dockerfile
    rootDir: .
